/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Model;

/**
 *
 * @author Luz Angela Melo
 */
public class Consultas extends javax.swing.JDialog {

    private DefaultTableModel modelo;

    /**
     * Creates new form Consultas
     */
    public Consultas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
        //CONSTRUIR LA TABLA
        modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Tipo");
        modelo.addColumn("Pais");
        modelo.addColumn("Combustible");
        modelo.addColumn("Empuje");
        jTableConsultas.setModel(modelo);
        List<Model> naves = new Controller().mostrarDatos();
        for (Model nave_espacial : naves) {
            String fila[] = {
                nave_espacial.getId() + "",
                nave_espacial.getNombre(),
                nave_espacial.getTipo(),
                nave_espacial.getPais(),
                nave_espacial.getCombustible() + "",
                nave_espacial.getEmpuje() + ""
            };
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConsultar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultas = new javax.swing.JTable();
        jComboBoxConsultas = new javax.swing.JComboBox<>();
        jTextFieldConsultas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonConsultar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonConsultar.setText("CONSULTAR");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 78, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelTitulo.setText("CONSULTAS");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 31, -1, -1));

        jTableConsultas.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jTableConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "TIPO", "PAIS", "COMBUSTIBLE", "EMPUJE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableConsultas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 123, 740, 150));

        jComboBoxConsultas.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jComboBoxConsultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOMBRE", "TIPO", "PAIS", " " }));
        getContentPane().add(jComboBoxConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 78, 180, -1));

        jTextFieldConsultas.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 78, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        // TODO add your handling code here:
        modelo.setRowCount(0);
        String Consultas = (String) jComboBoxConsultas.getSelectedItem();
        List<Model> naves = null;
        if (Consultas.equals("NOMBRE")) {
            naves = new ArrayList();
            naves.add(new Controller().buscarNave(jTextFieldConsultas.getText()));
        } else if (Consultas.equals("TIPO")) {
            naves = new Controller().buscarTipo(jTextFieldConsultas.getText());
        } else if (Consultas.equals("PAIS")) {
            naves = new Controller().buscarPais(jTextFieldConsultas.getText());
        }
        for (Model nave_espacial : naves) {
            String fila[] = {
                nave_espacial.getId() + "",
                nave_espacial.getNombre(),
                nave_espacial.getTipo(),
                nave_espacial.getPais(),
                nave_espacial.getCombustible() + "",
                nave_espacial.getEmpuje() + ""
            };
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Consultas dialog = new Consultas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JComboBox<String> jComboBoxConsultas;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultas;
    private javax.swing.JTextField jTextFieldConsultas;
    // End of variables declaration//GEN-END:variables
}
