/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import javax.swing.JOptionPane;
import model.Model;

/**
 *
 * @author Luz Angela Melo
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        jButtonActualizar.setEnabled(false);
        jButtonBorrar.setEnabled(false);
    }

    public void limpiar() {
        jTextFieldId.setText(null);
        jTextFieldNombre.setText(null);
        jTextFieldTipo.setText(null);
        jTextFieldPais.setText(null);
        jTextFieldCombustible.setText(null);
        jTextFieldEmpuje.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jLabelId = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelPais = new javax.swing.JLabel();
        jLabelCombustible = new javax.swing.JLabel();
        jLabelEmpuje = new javax.swing.JLabel();
        jTextFieldEmpuje = new javax.swing.JTextField();
        jButtonInsertar = new javax.swing.JButton();
        jButtonCargar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonConsultas = new javax.swing.JButton();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTipo = new javax.swing.JTextField();
        jTextFieldPais = new javax.swing.JTextField();
        jTextFieldCombustible = new javax.swing.JTextField();
        jTextFieldId1 = new javax.swing.JTextField();
        jTextFieldId2 = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(750, 600));
        setPreferredSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelId.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelId.setText("ID");
        jLabelId.setToolTipText("");
        getContentPane().add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 109, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelNombre.setText("NOMBRE");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 164, -1, -1));

        jLabelTipo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelTipo.setText("TIPO");
        getContentPane().add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 223, -1, -1));

        jLabelPais.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelPais.setText("PAIS");
        getContentPane().add(jLabelPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 290, -1, -1));

        jLabelCombustible.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelCombustible.setText("COMBUSTIBLE");
        getContentPane().add(jLabelCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 349, -1, -1));

        jLabelEmpuje.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabelEmpuje.setText("EMPUJE");
        getContentPane().add(jLabelEmpuje, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 414, -1, -1));

        jTextFieldEmpuje.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldEmpuje, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 411, 260, -1));

        jButtonInsertar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonInsertar.setText("INSERTAR");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 502, -1, -1));

        jButtonCargar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonCargar.setText("CARGAR");
        jButtonCargar.setToolTipText("");
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 502, -1, -1));

        jButtonActualizar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonActualizar.setText("ACTUALIZAR");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 502, -1, -1));

        jButtonBorrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonBorrar.setText("BORRAR");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 502, -1, -1));

        jButtonConsultas.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButtonConsultas.setText("CONSULTAS");
        jButtonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 502, -1, -1));

        jTextFieldId.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 106, 260, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 161, 260, -1));

        jTextFieldTipo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 220, 260, -1));

        jTextFieldPais.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 287, 260, -1));

        jTextFieldCombustible.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 346, 260, -1));

        jTextFieldId1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 106, 260, -1));

        jTextFieldId2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 106, 260, -1));

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 204, 204));
        jLabelTitulo.setText("NAVES ESPACIALES");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nave-espacial.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        // TODO add your handling code here:
        try {
            Model registro = new Model();
            try {
                registro.setId(Integer.parseInt(jTextFieldId.getText()));
            } catch (NumberFormatException exc) {
                registro.setId(0);
            }
            registro.setNombre(jTextFieldNombre.getText());
            registro.setTipo(jTextFieldTipo.getText());
            registro.setPais(jTextFieldPais.getText());
            try {
                registro.setCombustible(Double.parseDouble(jTextFieldCombustible.getText()));
            } catch (NumberFormatException exc) {
                registro.setCombustible(0.0);
            }
            try {
                registro.setEmpuje(Double.parseDouble(jTextFieldEmpuje.getText()));
            } catch (NumberFormatException exc) {
                registro.setEmpuje(0.0);
            }
            //CARGA LOS DATOS A TRAVÉ DE REGISTRO
            boolean resultado = new Controller().ingresarNave(registro);
            String mensaje = resultado ? "La nave espacial fue registrada" : "La nave espacial no fue registrada";
            limpiar();
            //IMPRIMIR MENSAJE
            JOptionPane.showMessageDialog(this, mensaje);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = jTextFieldNombre.getText();
            Model encontrado = new Controller().buscarNave(nombre);
            if (encontrado != null) {
                jTextFieldId.setText(encontrado.getId() + "");
                jTextFieldNombre.setText(encontrado.getNombre());
                jTextFieldTipo.setText(encontrado.getTipo());
                jTextFieldPais.setText(encontrado.getPais());
                jTextFieldCombustible.setText(encontrado.getCombustible() + "");
                jTextFieldEmpuje.setText(encontrado.getEmpuje() + "");
            } else {
                JOptionPane.showMessageDialog(this, "La nave espacial no se encuentra registrada");
                JOptionPane.showMessageDialog(this, "Ingrese nombre para cargar información");
            }
            jButtonActualizar.setEnabled(true);
            jButtonBorrar.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
    }//GEN-LAST:event_jButtonCargarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = jTextFieldNombre.getText();
            Model modificar = new Controller().buscarNave(nombre);
            if (modificar != null) {
                modificar.setTipo(jTextFieldTipo.getText());
                modificar.setPais(jTextFieldPais.getText());
                try {
                    modificar.setCombustible(Double.parseDouble(jTextFieldCombustible.getText()));
                } catch (NumberFormatException exc) {
                    modificar.setCombustible(0.0);
                }
                try {
                    modificar.setEmpuje(Double.parseDouble(jTextFieldEmpuje.getText()));
                } catch (NumberFormatException exc) {
                    modificar.setEmpuje(0.0);
                }
                //CARGA LOS DATOS A TRAVÉ DE MODIFICAR
                boolean resultado = new Controller().modificarNave(modificar);
                String mensaje = resultado ? "La nave espacial fue actualizada" : "La nave espacial no fue actualizada";
                limpiar();
                //IMPRIMIR MENSAJE
                JOptionPane.showMessageDialog(this, mensaje);
            } else {
                JOptionPane.showMessageDialog(this, "La nave espacial no se encuentra registrada");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // TODO add your handling code here:
        try {
            Integer id = Integer.parseInt(jTextFieldId.getText());
            Model nave = new Controller().buscarNaveId(id);
            if (nave != null) {
                boolean resultado = new Controller().borrarNave(nave);
                String mensaje = resultado ? "La nave espacial fue borrada" : "La nave espacial no fue borrada";
                limpiar();
                //IMPRIMIR MENSAJE
                JOptionPane.showMessageDialog(this, mensaje);
            } else {
                JOptionPane.showMessageDialog(this, "La nave espacial no se encuentra registrada");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultasActionPerformed
        // TODO add your handling code here:
        new Consultas(this, true).setVisible(true);
    }//GEN-LAST:event_jButtonConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonConsultas;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCombustible;
    private javax.swing.JLabel jLabelEmpuje;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldCombustible;
    private javax.swing.JTextField jTextFieldEmpuje;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldId1;
    private javax.swing.JTextField jTextFieldId2;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPais;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
